### PR TITLE
Support for Java 11

### PR DESCRIPTION
**Pull request by MarioKusek**

### CODE REVIEW

**Comment by mjacoby** [comment]
Hi Mario. I am aware of the pull request but I currently do not have to the to check it. Also I do not have a Java 11 environment set up. Therefore, this might take a while.

Also, it seems I don't have the rights to merge this pull request as it says "You're not authorized to merge this pull request".

**Comment by MarioKusek** [comment]
@mjacoby I don't have rights as well. I will investigate who has it and ask to give you rights. If you wish and think that I can do it as well then I will ask for rights as well. But only if you agree with that.

Regarding Java 11 I just removed Pair from javaFX because it is no longer in Java 11 and instead of that I have used Pair from apache commons library that is already in dependencies. Everything else is the same. All tests are passing and Travis checked build.

**Review by mjacoby — APPROVED** [review]

**Comment by mjacoby** [comment]
I approved your changes but still can't merge because of missing rights. I assume @vthglyk might have the rights but might be difficult to get in touch with him.
It's also ok for me if you manage to get yourself the rights and merge the PR.

**Comment by iliapietri** [comment]
Hi @mjacoby, @MarioKusek! Vassilis has departed from the company, but I might be able to help. What rights do you need? How can I help?

**Comment by MarioKusek** [comment]
@iliapietri We need rights to merge or to push to master branch. I also need the same right for RAP repository as well. Master branch is protected and only some users can push or merge to it. I don't know what exact right is that.

**Pull request merged**
